### ISSUE TITLE
Netlify用設定ファイルの設置

### ISSUE THREAD

**Issue by hkawa90** [hkawa90/astro-starlight-obsidian-template#11]
下記netlify.tomlを用意しておく

```toml
[build]
  command = "pnpm run build"
  publish = "dist"
```
