### ISSUE TITLE
GitHub Pageへdeployするとwiki link([[page name]])がastoro.config.mjsで設定したbaseが付与されないため404と表示される

### ISSUE THREAD

**Issue by hkawa90** [hkawa90/astro-starlight-obsidian-template#9]
AstroではGithub Pageではconfigとして、`site`に`https://<user name>.github.io`, `base`に`repository name`を設定するが、

```js title="astro.config.mjs"
export default defineConfig({
	site: siteName,
	base: baseName,
```

wiki linkが`base`が参照されず、`https;//<user name>.github.io/<wiki link>`となってしまいページがないとみなされる。

**Comment by hkawa90** [comment]
wikilinkはビルドされたhtmlをみると、`base`の内容が展開されていない。
```html
<a href="/notes/npm">NPM</a>
```
Astro docsによれば下記の通り。

> Caution
> When this value is configured, all of your internal page links must be prefixed with your base value:

このためObsidian pluginの問題でないことから、workaroundで
```html
<a href="/notes
```
をビルド後に
```html
<a href="${repository}/notes
```
に変換する。

**Comment by hkawa90** [comment]
[YAML Read · Actions · GitHub Marketplace · GitHub](https://github.com/marketplace/actions/yaml-read)とsedで変換できることを確認

```yaml
name: Test Actions

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  # push:
  #   branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write
# https://stackoverflow.com/questions/58467939/is-there-a-way-to-get-the-project-folder-name-only-on-a-github-action
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
          config: ${{ github.workspace }}/config.yaml

      - name: use-yaml-file
        run: find . -name "*.html" -print | xargs sed -i s@href=\"/${{ steps.read_action_js.outputs['note'] }}@href=\"/${{ github.event.repository.name }}/${{ steps.read_action_js.outputs['note'] }}@
      - name: bbb
        run: cat index.html
```
